### ISSUE TITLE
Labels PCB

### ISSUE THREAD

**Issue by ChroustJan** [mlab-modules/BP02#1]
@kaklik  nebylo by vhodné označit vstup a výstup na PCB:
![image](https://user-images.githubusercontent.com/9783606/118599445-cf4caa80-b7af-11eb-9242-f6b7063c72dd.png)

**Comment by kaklik** [comment]
Zkusil jsem jednoznačnost potisku vylepšit přidáním symbolu RF filtru a označit různorodost řádů filtrů na konektorech.

![image](https://user-images.githubusercontent.com/1194177/118619854-3fb1f680-b7c5-11eb-9a83-316a526b60fb.png)
