### ISSUE TITLE
Add correct identificators for OpenIntranet warehouse

### ISSUE THREAD

**Issue by kaklik** [mlab-modules/BP02#2]
Přidat správná označení [UST_ID](https://github.com/UniversalScientificTechnologies/OpenIntranet/wiki/KiCAD) k použitým součástkám.

**Comment by kaklik** [comment]
UST_ID jsou přiřazené. Je to ke kontrole @ChroustJan

**Comment by ChroustJan** [comment]
UST ID mi přijde dobré. @kaklik je potřeba uklidit B.FAB pro tisk.

**Comment by kaklik** [comment]
>@kaklik je potřeba uklidit B.FAB pro tisk.

Provedeno.

**Comment by ChroustJan** [comment]
V pořádku
